# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2fafb66a355a2f04f4420ad721ad374227dff40ef905bfd0f4d01f5fca244928db23cf3fec0efe15f5c2909ee75d06186283415199c2360b23167fb24e9361

test:
  secret_key_base: 039fccd446541935c9549b425499702f572622798f4c802f0dd7e90c9d601f2fde00ca689501ce1009a01bd35996beadb10ad27afea54ddf9d625bcd105ac92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
